Repository CA-G12/E-Commerce-Team-4, pull requests merged in 2022-09, with the labels that each got.

#10 created database table schema thats has three table one for users, pr…
  server/database/config/schema.sql
Labels: Awaiting-review

#19 edit schema
  server/database/config/schema.sql
Labels: Awaiting-review

#15 Cart queries.
  server/database/queries/cart/deleteProductFromCart.js
  server/database/queries/cart/getCartProductsForUser.js
  server/database/queries/cart/index.js
  server/database/queries/index.js
Labels: Awaiting-review

#16 create login query
  server/database/queries/auth/checkEmail.js
  server/database/queries/auth/getPassword.js
  server/routes/index.js
  server/utils/validation/validateLogin.js
Labels: Approved

#20 8 create sign up query
  client/public/index.html
  server/database/index.js
  server/database/queries/index.js
  server/database/queries/users/index.js
  server/database/queries/users/signUpQuery.js
  server/utils/validation/validateSignup.js
Labels: Approved

#25 get all products (by price ,category )
  server/controllers/index.js
  server/controllers/products/getProducts.js
  server/controllers/products/index.js
  server/database/queries/products/getAllProducts.js
  server/database/queries/products/index.js
  server/routes/products.js
Labels: Awaiting-review

#30 create controller login
  server/controllers/auth/index.js
  server/controllers/auth/login.js
  server/database/config/schema.sql
  server/database/queries/auth/index.js
  server/routes/auth.js
  server/utils/validation/index.js
  server/utils/validation/validateLogin.js
Labels: Approved

#31 Added the readme documentation file
  README.md
Labels: Awaiting-review

#32 21 create signup controllers functions
  server/controllers/auth/index.js
  server/controllers/auth/signup.js
  server/controllers/index.js
  server/database/queries/users/signUpQuery.js
  server/routes/users.js
  server/utils/index.js
  server/utils/validation/index.js
  server/utils/validation/validateLogin.js
  server/utils/validation/validateSignup.js
Labels: Awaiting-review

#54 33 landing page
  client/public/index.html
  client/src/Components/App.css
  client/src/Components/App.jsx
  client/src/Components/LandingPage/Categories/Categories.css
  client/src/Components/LandingPage/Categories/Categories.jsx
  client/src/Components/LandingPage/Footer/Footer.css
  client/src/Components/LandingPage/Footer/Footer.jsx
  client/src/Components/LandingPage/Header/Header.css
  client/src/Components/LandingPage/Header/Header.jsx
  client/src/Components/LandingPage/LandingImage/LandingImage.css
  client/src/Components/LandingPage/LandingImage/LandingImage.jsx
  client/src/Components/LandingPage/LandingImage/image.jpg
  client/src/Components/LandingPage/LandingPage.css
  client/src/Components/LandingPage/LandingPage.jsx
  client/src/Components/LandingPage/Products/Filter/Filter.jsx
  client/src/Components/LandingPage/Products/Filter/FilterCategory.jsx
  client/src/Components/LandingPage/Products/Filter/FilterPrice.jsx
  client/src/Components/LandingPage/Products/Filter/filter.css
  client/src/Components/LandingPage/Products/Product/Product.css
  client/src/Components/LandingPage/Products/Product/Product.jsx
  client/src/Components/LandingPage/Products/Products.css
  client/src/Components/LandingPage/Products/Products.jsx
Labels: Approved

#55 deleted image component.
  client/src/Components/LandingPage/LandingImage/LandingImage.css
  client/src/Components/LandingPage/LandingImage/LandingImage.jsx
  client/src/Components/LandingPage/LandingImage/image.jpg
  client/src/Components/LandingPage/LandingPage.jsx
Labels: Awaiting-review

#56 fix eslint
  .prettierrc.json
  .vscode/settings.json
  client/.eslintrc.js
  client/package.json
  client/src/Components/App.jsx
  package-lock.json
  package.json
  server/.eslintrc.json
  server/app.js
  server/controllers/auth/login.js
  server/controllers/auth/signup.js
  server/controllers/index.js
  server/controllers/products/getProducts.js
  server/controllers/products/index.js
  server/database/config/buildFakeData.js
  server/database/config/buildSchema.js
  server/database/config/connection.js
  server/database/queries/auth/index.js
  server/database/queries/cart/postToCart.js
  server/database/queries/index.js
  server/database/queries/products/getAllProducts.js
  server/database/queries/products/index.js
  server/database/queries/users/index.js
  server/database/queries/users/signUpQuery.js
  server/index.js
  server/routes/auth.js
  server/routes/products.js
  server/routes/users.js
  server/utils/index.js
  server/utils/validation/validateLogin.js
  server/utils/validation/validateSignup.js
Labels: Approved

#57 Created login component and styled it.
  client/src/Components/Login/Login.css
  client/src/Components/Login/Login.jsx
Labels: Approved

#58 Created signup component and styled it.
  client/src/Components/Signup/Signup.css
  client/src/Components/Signup/Signup.jsx
Labels: Approved

#63 62 create all products section functionality
  client/package-lock.json
  client/package.json
  client/src/Components/App.jsx
  client/src/Components/LandingPage/LandingPage.jsx
  client/src/Components/LandingPage/Products/Filter/FilterCategory.jsx
  client/src/Components/LandingPage/Products/Filter/FilterPrice.jsx
  client/src/Components/LandingPage/Products/Product/Product.jsx
  client/src/Components/LandingPage/Products/Products.jsx
  client/src/Components/Login/Login.css
  client/src/Components/Signup/Signup.css
  package-lock.json
  package.json
Labels: Awaiting-review

#66 create cart
  client/.eslintrc.js
  client/package-lock.json
  client/package.json
  client/src/Components/App.jsx
  client/src/Components/Cart/Cart.jsx
  client/src/Components/Cart/Header/Header.css
  client/src/Components/Cart/Header/Header.jsx
  client/src/Components/Cart/Products/Pagenation/Pagenation.css
  client/src/Components/Cart/Products/Pagenation/Pagenation.jsx
  client/src/Components/Cart/Products/Product/Product.css
  client/src/Components/Cart/Products/Product/Product.jsx
  client/src/Components/Cart/Products/Products.css
  client/src/Components/Cart/Products/Products.jsx
Labels: Awaiting-review

#67 fix conflict in app.jsx file
  client/package.json
  client/src/Components/App.jsx
  client/src/index.jsx
Labels: Awaiting-review

#70 create pagination to show more products
  client/src/Components/LandingPage/Products/Filter/filter.css
  client/src/Components/LandingPage/Products/Products.css
  client/src/Components/LandingPage/Products/Products.jsx
  server/controllers/products/getProducts.js
  server/database/queries/products/getAllProducts.js
  server/routes/products.js
Labels: Awaiting-review

#68 Create login signup requests.
  client/.eslintrc.js
  client/package-lock.json
  client/package.json
  client/src/Components/Login/Login.css
  client/src/Components/Login/Login.jsx
  client/src/Components/Signup/Signup.css
  client/src/Components/Signup/Signup.jsx
  server/controllers/auth/login.js
  server/controllers/auth/signup.js
  server/database/queries/auth/addUserSignup.js
  server/database/queries/auth/getAccount.js
  server/database/queries/auth/index.js
  server/database/queries/index.js
  server/database/queries/users/index.js
  server/database/queries/users/signUpQuery.js
  server/utils/index.js
  server/utils/validation/validateLogin.js
  server/utils/validation/validateSignup.js
Labels: Awaiting-review

#71 61 handle sort by price functionality
  client/package.json
  client/src/Components/LandingPage/Products/Filter/Filter.jsx
  client/src/Components/LandingPage/Products/Filter/FilterPrice.jsx
  client/src/Components/LandingPage/Products/Products.jsx
  server/app.js
Labels: In-progress

#73 fix show more
  client/src/Components/LandingPage/Products/Products.jsx
  server/database/queries/products/getAllProducts.js
Labels: Awaiting-review

#74 72 create product details component
  client/src/Components/App.jsx
  client/src/Components/Cart/Cart.jsx
  client/src/Components/Cart/Footer/Footer.css
  client/src/Components/Cart/Footer/Footer.jsx
  client/src/Components/Cart/Header/Header.css
  client/src/Components/Cart/Header/Header.jsx
  client/src/Components/Footer/Footer.css
  client/src/Components/Footer/Footer.jsx
  client/src/Components/Header/Header.css
  client/src/Components/Header/Header.jsx
  client/src/Components/LandingPage/LandingPage.jsx
  client/src/Components/LandingPage/Products/Product/Product.jsx
  client/src/Components/Product/Details/Details.jsx
  client/src/Components/Product/Footer/Footer.css
  client/src/Components/Product/Footer/Footer.jsx
  client/src/Components/Product/Header/Header.css
  client/src/Components/Product/Header/Header.jsx
  client/src/Components/Product/Product.jsx
  server/controllers/cart/postToCart.js
  server/controllers/index.js
  server/controllers/products/getOneProduct.js
  server/controllers/products/index.js
  server/controllers/products/productDetails.js
  server/database/queries/index.js
  server/database/queries/products/getOneProduct.js
  server/database/queries/products/index.js
  server/database/queries/products/productDetailsQuery.js
  server/routes/products.js
Labels: Awaiting-review

#75 50 51 cart component
  client/public/index.html
  client/src/Components/Cart/Products/Product/Product.css
  client/src/Components/Cart/Products/Product/Product.jsx
  client/src/Components/Cart/Products/Products.css
  client/src/Components/Cart/Products/Products.jsx
  server/controllers/cart/getCartProduct.js
  server/database/config/fakeData.sql
  server/database/queries/cart/getCartProductsForUser.js
Labels: Approved

#77 Delete a product from cart
  .vscode/settings.json
  client/package-lock.json
  client/package.json
  client/src/Components/Cart/Cart.css
  client/src/Components/Cart/Cart.jsx
  client/src/Components/Cart/Products/Product/Product.jsx
  client/src/Components/Cart/Products/Products.jsx
  client/src/Components/Header/Header.css
  server/controllers/cart/deleteFromCart.js
  server/routes/cart.js
Labels: Approved

#80 79 create links between pages and create add to cart functionailty
  client/src/Components/App.css
  client/src/Components/Cart/Cart.jsx
  client/src/Components/Cart/Products/Product/Product.jsx
  client/src/Components/Header/Header.jsx
  client/src/Components/LandingPage/Products/Product/Product.css
  client/src/Components/LandingPage/Products/Product/Product.jsx
  client/src/Components/LandingPage/Products/Products.jsx
  client/src/Components/Product/Details/Details.jsx
  client/src/Components/Product/Product.jsx
  server/controllers/auth/checkLogin.js
  server/controllers/auth/index.js
  server/controllers/index.js
  server/routes/auth.js
Labels: Approved

#82 43 create product page footer component
  client/src/Components/Footer/Footer.css
  client/src/Components/Footer/Footer.jsx
  client/src/Components/LandingPage/Categories/Categories.css
  client/src/Components/LandingPage/Products/Filter/FilterCategory.jsx
  client/src/Components/LandingPage/Products/Filter/FilterPrice.jsx
  client/src/Components/LandingPage/Products/Filter/filter.css
  client/src/Components/LandingPage/Products/Product/Product.css
  client/src/Components/LandingPage/Products/Products.css
  client/src/Components/LandingPage/Products/Products.jsx
Labels: Awaiting-review

#84 Added cart, login, signup enhancements.
  client/src/Components/Cart/Products/Product/Product.jsx
  client/src/Components/Cart/Products/Products.jsx
  client/src/Components/Login/Login.css
  client/src/Components/Login/Login.jsx
  client/src/Components/Signup/Signup.css
  client/src/Components/Signup/Signup.jsx
  server/controllers/auth/login.js
Labels: Awaiting-review

#85 add fake data and edit query
  server/database/config/fakeData.sql
  server/database/queries/products/getAllProducts.js
Labels: Awaiting-review

#87 Fix products card styling
  client/src/Components/LandingPage/Products/Filter/filter.css
  client/src/Components/LandingPage/Products/Product/Product.css
Labels: Awaiting-review

#88 handle fake data
  server/database/config/fakeData.sql
Labels: Awaiting-review

#90 78 style product details component
  client/src/Components/Cart/Products/Product/Product.css
  client/src/Components/Cart/Products/Product/Product.jsx
  client/src/Components/Cart/Products/Products.css
  client/src/Components/Cart/Products/Products.jsx
Labels: Awaiting-review
